### ISSUE TITLE
chainparams.cpp

### ISSUE THREAD

**Issue by grand96** [antares-codes/metaaco#1]
chainparams.cpp:251: CMainParams::CMainParams(): Assertion `hashGenesisBlock == uint256("0x00000179c2edcadbffebb5d3940e6fe018d8905df41a73bbc9f6f350547ed684")' failed.

**Comment by antares-codes** [comment]
The coin launch on August 1st, 2022.

check line 235 const char* pszTimestamp = "Do Not Compile Genesis not yet created";
